In [1]:
import numpy as np
import csv
import math as m
import scipy.constants as sp

test=0
# constants
k_b=sp.k # boltzman const(k_b) in SI
sig = sp.sigma # stefan boltzmann constant
c=sp.c # speed of light
h=sp.h # Planck's const
pi=np.pi # pi


# emmisivity, refl, trans  csv data transferred into matrix 
e=np.array(list(csv.reader(open("repository/repo/TER_file_cryorun7_emiss.csv","r"),delimiter=','))).astype('float')
d_r=np.array(list(csv.reader(open("repository/repo/TER_file_cryorun7_refl.csv","r"),delimiter=','))).astype('float')
t=np.array(list(csv.reader(open("repository/repo/TER_file_cryorun7_trans.csv","r"),delimiter=','))).astype('float')
s_r=np.array(list(csv.reader(open("repository/repo/spec refl.csv","r"),delimiter=','))).astype('float')

A=[]
A=np.random.rand(6000,13)
AA= A*(10**-21)

In [4]:
# test E's will bring from the prev program

#   E_mat = [5, 4.8, 4.4, 3.6, 2, .8, .05, .002, .0004, .00006, .000009,.0000005 ]

c=0 # counter

#for i in range (0,6001):   #  the loop for going over 4 different areas of the circuit, for now testing the 2nd part





# R mat

R_mat=[]

E_mat= E[k]    # the E from program Newer versionn (comparing tot P) ... gives the E of an element for a particular waveno.
for c in (1,3,5,7,9,11):              #  the loop for going over 6 different areas of the circuit  (7x6)=42 equations (step 1) + 5 more remaining for transmission over filters 3, 5, 7, 9 & 11 (step 2) 
    R_mat= np.array([[1,1,-1,0,0,0,0,0], [0,0,1,-1,-1,0,0,0], [0,0,0,0,1,1,-1,0],[0,0,0,0,0,0,1,-1], [0,R[c+1],R[c+2],R[c+3],0,0,0,0], [0,0,0,0,0,R[c+5],R[c+6],R[c+7]],[0,R[c+1],R[c+2],0,R[c+4],0,R[c+6],R[c+7]], np.int32)
    
    J= np.linalg.inv(R_mat)*E_mat               # E at specific wavenumber
    J_most= np.append(J_most,J)
    
    

0
1
2
3


In [11]:
J_most=[[1, 2, 3], [4, 5, 6]]
J=[1, 9, 3]
J_most.append(J)
J_most=np.array(J_most)
print (J_most)
J= np.linalg.inv(J_most)
print (J)

[[1 2 3]
 [4 5 6]
 [1 9 3]]
[[-0.92857143  0.5        -0.07142857]
 [-0.14285714  0.          0.14285714]
 [ 0.73809524 -0.16666667 -0.07142857]]
