In [25]:
import numpy as np
R= np.array([[1.,-1.,0.,0.,-1], [0.,-1.,1.,1.,0], [3.,2.,9.,0.,0.], [3.,2.,0.,8.,0.], [3.,0.,0.,0.,4.]])
print R
import csv
with open("R.csv", "wb") as fi:
    writer = csv.writer(fi)
    writer.writerows(R)
print
print

def convert_to_float(arr):
    test_arr = []
    for i in arr:
        try:
            test_arr.append(float(i))
        #y = item.astype(np.float)
        except:
            #test_arr.append(i)
            a = 1
    return test_arr

RR=[]
with open('R.csv', 'rb') as csvfile:
    spr = csv.reader(csvfile, delimiter=' ', quotechar='|')
    for row in spr:
        print row
        tst_arr= row[0].split(',')
        z = convert_to_float(tst_arr)
        print tst_arr
        print "*" + str(z) + "*"
        RR.append(z)
        #RR= np.vstack([RR, z])  #: doesn't work???
        
print RR
RR = np.array(RR)
from numpy.linalg import inv
R_inv= inv(RR)
V= ([[0],[0],[30], [30], [30]])
print V
print
print
I= np.dot(R_inv, V)
print I

[[ 1. -1.  0.  0. -1.]
 [ 0. -1.  1.  1.  0.]
 [ 3.  2.  9.  0.  0.]
 [ 3.  2.  0.  8.  0.]
 [ 3.  0.  0.  0.  4.]]


['1.0,-1.0,0.0,0.0,-1.0']
['1.0', '-1.0', '0.0', '0.0', '-1.0']
*[1.0, -1.0, 0.0, 0.0, -1.0]*
['0.0,-1.0,1.0,1.0,0.0']
['0.0', '-1.0', '1.0', '1.0', '0.0']
*[0.0, -1.0, 1.0, 1.0, 0.0]*
['3.0,2.0,9.0,0.0,0.0']
['3.0', '2.0', '9.0', '0.0', '0.0']
*[3.0, 2.0, 9.0, 0.0, 0.0]*
['3.0,2.0,0.0,8.0,0.0']
['3.0', '2.0', '0.0', '8.0', '0.0']
*[3.0, 2.0, 0.0, 8.0, 0.0]*
['3.0,0.0,0.0,0.0,4.0']
['3.0', '0.0', '0.0', '0.0', '4.0']
*[3.0, 0.0, 0.0, 0.0, 4.0]*
[[1.0, -1.0, 0.0, 0.0, -1.0], [0.0, -1.0, 1.0, 1.0, 0.0], [3.0, 2.0, 9.0, 0.0, 0.0], [3.0, 2.0, 0.0, 8.0, 0.0], [3.0, 0.0, 0.0, 0.0, 4.0]]
[[0], [0], [30], [30], [30]]


[[ 5.5179704 ]
 [ 2.1564482 ]
 [ 1.01479915]
 [ 1.14164905]
 [ 3.3615222 ]]
